#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
DeepLabCut (DLC) Training, Evaluation, and Video Processing Script

End-to-end pipeline that:
1. Updates the DLC ``config.yaml`` with current paths and video sets.
2. Creates a training dataset from labeled frames.
3. Trains a DLC network (ResNet-based pose estimation) up to a specified
   number of iterations, saving periodic snapshots.
4. Evaluates every saved snapshot and selects the one with the lowest
   test error (RMSE in pixels).
5. Runs inference and creates labeled videos using either the *best*
   snapshot, the *most-trained* (final) snapshot, or both.

Prerequisites
-------------
- DeepLabCut (tested with DLC 2.x / 3.x)
- TensorFlow (GPU build recommended)
- A DLC project with labeled frames already created via
  ``deeplabcut.label_frames()`` or equivalent.

Usage
-----
1. Set ``CONFIG_PATH`` and ``PROJECT_PATH`` to your DLC project.
2. Adjust training hyper-parameters (``MAXITERS``, ``SAVEITERS``, etc.).
3. Choose ``PROCESS_OPTION``: "best", "most", or "both".
4. Run:  ``python dlc_training.py``

Output
------
- Trained model snapshots under ``<project>/dlc-models/``.
- Evaluation CSVs and plots under ``<project>/evaluation-results/``.
- Inference CSVs and labeled videos alongside the source videos.
"""

import os
import sys
import deeplabcut
import yaml
import glob
import pandas as pd
import pickle
from datetime import datetime
import tensorflow as tf
from pathlib import Path

# ============================================================================
# User Options
# ============================================================================
# "both"  — run inference with best snapshot AND with the most-trained snapshot
# "best"  — inference only with the snapshot that has the lowest test error
# "most"  — inference only with the final (most-trained) snapshot
PROCESS_OPTION = "most"

# ============================================================================
# Paths — UPDATE THESE for your environment
# ============================================================================
# Absolute path to the DLC project's config.yaml.
# This file is auto-generated by deeplabcut.create_new_project() and contains
# model architecture, body-part definitions, and video-set metadata.
CONFIG_PATH = "<DLC_PROJECT_DIR>/config.yaml"
# Example: "/path/to/dlc-project-YYYY-MM-DD/config.yaml"

# Root directory of the DLC project (parent of config.yaml).
PROJECT_PATH = "<DLC_PROJECT_DIR>"
# Example: "/path/to/dlc-project-YYYY-MM-DD"

# Task name used in the DLC project (must match config.yaml 'Task' key).
TASK_NAME = "<TASK_NAME>"
# Example: "sturgeon", "zebrafish", "eel"

# Training fraction — proportion of labeled frames used for training.
TRAINING_FRACTION = 0.95

# DLC project iteration number (incremented when you add more labeled data).
PROJECT_ITERATION = 5

# Video crop string (DLC format: "x1, x2, y1, y2").
# Set to None to disable cropping.
VIDEO_CROP = "0, 1024, 0, 1024"

# ============================================================================
# Training Hyper-parameters
# ============================================================================
MAXITERS              = 1_000_000   # Total training iterations
SAVEITERS             = 100_000     # Save a snapshot every N iterations
MAX_SNAPSHOTS_TO_KEEP = None        # None = keep all snapshots
SHUFFLE_NUM           = 1           # DLC shuffle index
GPU_TO_USE            = 0           # GPU index for training

# ============================================================================
# Version Check
# ============================================================================
print(f"DeepLabCut version: {deeplabcut.__version__}")
try:
    print(f"TensorFlow version: {tf.__version__}")
except ImportError:
    print("TensorFlow is not installed.")
    sys.exit(1)

# ============================================================================
# GPU Configuration
# ============================================================================
os.environ["CUDA_VISIBLE_DEVICES"] = str(GPU_TO_USE)

gpus = tf.config.list_physical_devices('GPU')
if gpus:
    try:
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
        logical_gpus = tf.config.list_logical_devices('GPU')
        print(f"{len(gpus)} Physical GPU(s), {len(logical_gpus)} Logical GPU(s) detected.")
    except RuntimeError as e:
        print(f"Error setting memory growth: {e}")
else:
    print("No GPUs detected. Using CPU.")

# ============================================================================
# Update config.yaml — paths and video sets
# ============================================================================
config_path = CONFIG_PATH
with open(config_path, 'r') as f:
    config = yaml.safe_load(f)

if 'Task' not in config:
    config['Task'] = TASK_NAME
if 'TrainingFraction' not in config:
    config['TrainingFraction'] = [TRAINING_FRACTION]

config['project_path'] = PROJECT_PATH
config['date'] = datetime.now().strftime('%b%d')
config['iteration'] = PROJECT_ITERATION

project_path = Path(config['project_path'])
videos_dir = project_path / 'videos'

# Collect videos from top-level videos/ only (non-recursive)
VIDEO_EXTS = {'.mp4', '.avi', '.mov', '.mkv'}
videos_paths = sorted(
    [p for p in videos_dir.iterdir() if p.is_file() and p.suffix.lower() in VIDEO_EXTS],
    key=lambda p: p.name
)

videos = [str(p) for p in videos_paths]

video_sets = {}
for p in videos_paths:
    entry = {}
    if VIDEO_CROP is not None:
        entry['crop'] = VIDEO_CROP
    video_sets[str(p)] = entry
config['video_sets'] = video_sets

with open(config_path, 'w') as f:
    yaml.dump(config, f, default_flow_style=False, sort_keys=False)

print(f"Synced {len(videos)} videos from {videos_dir} into config['video_sets'].")
print(f"Config.yaml 'date' field has been updated to {config['date']}.")

# ============================================================================
# Create Training Dataset
# ============================================================================
deeplabcut.create_training_dataset(config_path)
deeplabcut.check_labels(config_path)
print("Training dataset has been created from labeled data.")

# ============================================================================
# Train Network
# ============================================================================
deeplabcut.train_network(
    config_path,
    shuffle=SHUFFLE_NUM,
    trainingsetindex=0,
    maxiters=MAXITERS,
    displayiters=100,
    saveiters=SAVEITERS,
    allow_growth=True,
    gputouse=GPU_TO_USE,
    max_snapshots_to_keep=MAX_SNAPSHOTS_TO_KEEP,
)

print("Training completed.")

# ============================================================================
# Evaluate All Saved Snapshots — pick the best one
# ============================================================================
snapshots_to_evaluate = list(range(SAVEITERS, MAXITERS + 1, SAVEITERS))
best_snapshot_index = None
best_rmse = float('inf')
best_iteration = None

train_path = deeplabcut.return_train_network_path(
    config_path, shuffle=SHUFFLE_NUM, trainingsetindex=0
)[-1]
pose_cfg_path = os.path.join(train_path, 'pose_cfg.yaml')
if not os.path.isfile(pose_cfg_path):
    print(f"Error: pose_cfg.yaml not found at {pose_cfg_path}.")
    sys.exit(1)

with open(pose_cfg_path, 'r') as f:
    pose_cfg = yaml.safe_load(f)

if 'net_type' in pose_cfg:
    net_type = pose_cfg['net_type']
    config['net_type'] = net_type
else:
    print("Error: 'net_type' not found in pose_cfg.yaml.")
    sys.exit(1)

net_type_file = net_type.replace('_', '')
dataset_path = pose_cfg['dataset']
iteration_dir = dataset_path.split('/')[1]
print(f"Extracted iteration directory: {iteration_dir}")

snapshot_folder = os.path.join(train_path)
snapshot_pattern = os.path.join(snapshot_folder, 'snapshot-*.index')
snapshot_files = sorted(glob.glob(snapshot_pattern), key=os.path.getmtime)
snapshot_index_map = {}
for idx, snapshot_file in enumerate(snapshot_files):
    filename = os.path.basename(snapshot_file)
    iter_num = int(filename.split('-')[1].split('.')[0])
    snapshot_index_map[iter_num] = idx

for iteration in snapshots_to_evaluate:
    if iteration not in snapshot_index_map:
        print(f"Snapshot for iteration {iteration} not found.")
        continue

    idx = snapshot_index_map[iteration]
    print(f"Evaluating snapshot at index {idx}, iteration {iteration}...")

    config['snapshotindex'] = idx
    modelprefix = (
        f"DLC_{net_type_file}_{config['Task']}{config['date']}"
        f"shuffle{SHUFFLE_NUM}_{iteration}"
    )
    with open(config_path, 'w') as f:
        yaml.dump(config, f, default_flow_style=False, sort_keys=False)

    deeplabcut.evaluate_network(
        config_path,
        Shuffles=[SHUFFLE_NUM],
        trainingsetindex=0,
        plotting=True,
        gputouse=GPU_TO_USE,
    )

    eval_results_dir = os.path.join(
        config['project_path'],
        'evaluation-results',
        iteration_dir,
        f"{config['Task']}{config['date']}-trainset"
        f"{int(config['TrainingFraction'][0] * 100)}shuffle{SHUFFLE_NUM}"
    )

    csv_file_pattern = os.path.join(eval_results_dir, f"*{iteration}-results.csv")
    csv_files = glob.glob(csv_file_pattern)
    if not csv_files:
        print(f"No evaluation CSV file found for iteration {iteration}.")
        continue

    eval_csv_file = csv_files[0]
    try:
        eval_df = pd.read_csv(eval_csv_file)
    except Exception as e:
        print(f"Error reading evaluation CSV file for iteration {iteration}: {e}")
        continue

    eval_df.columns = eval_df.columns.str.strip()
    test_error_col = None
    for col in eval_df.columns:
        if col.strip() == 'Test error(px)':
            test_error_col = col
            break

    if test_error_col:
        test_error = eval_df[test_error_col].values[0]
    else:
        print(
            f"'Test error(px)' column not found for iteration {iteration}. "
            f"Available columns: {eval_df.columns}"
        )
        continue

    print(f"Snapshot at index {idx}, iteration {iteration} — Test error(px): {test_error}")

    if test_error < best_rmse:
        best_rmse = test_error
        best_snapshot_index = idx
        best_iteration = iteration

if best_snapshot_index is not None:
    print(
        f"Best snapshot index is '{best_snapshot_index}' "
        f"(iteration {best_iteration}) with Test error(px): {best_rmse}"
    )
    config['snapshotindex'] = best_snapshot_index
    with open(config_path, 'w') as f:
        yaml.dump(config, f, default_flow_style=False, sort_keys=False)
else:
    print("No valid snapshots were evaluated. Cannot proceed with analysis.")
    sys.exit(1)

# ============================================================================
# Video Processing — inference + labeled videos
# ============================================================================
if PROCESS_OPTION in ["both", "best"]:
    print("Processing videos using the best model:")
    deeplabcut.analyze_videos(
        config_path, videos, shuffle=SHUFFLE_NUM, save_as_csv=True,
    )
    print("Creating labeled videos using the best model:")
    deeplabcut.create_labeled_video(
        config_path, videos, shuffle=SHUFFLE_NUM,
    )

if PROCESS_OPTION in ["both", "most"]:
    config['snapshotindex'] = -1
    with open(config_path, 'w') as f:
        yaml.dump(config, f, default_flow_style=False, sort_keys=False)
    print("Updated config to use the most trained model (snapshotindex = -1)")

    print("Analyzing videos using the most trained model:")
    deeplabcut.analyze_videos(
        config_path, videos, shuffle=SHUFFLE_NUM, save_as_csv=True,
    )
    print("Creating labeled videos using the most trained model:")
    deeplabcut.create_labeled_video(
        config_path, videos, shuffle=SHUFFLE_NUM,
    )

print("Video processing completed based on the selected option.")
sys.exit(0)
